env:
  es6: true
  node: true
  "jest/globals": true
extends:
  - "plugin:jest/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - jest
rules: {}
