env:
  es6: true
  node: true
extends: 'plugin:mocha/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - mocha
rules: {
  "mocha/no-hooks-for-single-case": "off"
}
