name: Smoke Tests
on:
  repository_dispatch:
    types: [ smoke_test_trigger ]

env:
  NODE_VERSION: '12.16.3'
  BASE_RETURNS_URL: 'https://peachreturns.z13.web.core.windows.net'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  smoke_test:
    name: Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: debugging output
        run: echo "${{ github.event.type }} - ${{ github.event_name }}"
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: BASE_RETURNS_URL=${{ env.BASE_RETURNS_URL }} npm run test
      - name: Emit smoke test success to app for release
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ruelala/${{ github.event.client_payload.application }}
          event-type: 'deploy-event'
          client-payload: '{ "branch": "${{ github.event.client_payload.branch }}", "fleet": "${{ github.event.client_payload.fleet }}" }'
