name: Smoke Tests
on:
  repository_dispatch:
    types: [ smoke_test_trigger ]

env:
  NODE_VERSION: '12.16.3'
  BASE_RETURNS_URL: 'https://peachreturns.z13.web.core.windows.net'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  smoke_test:
    name: Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: debugging output
        run: echo "${{ github.event_name }} - ${{ github.event.client_payload.application }} - ${{ github.event.client_payload.release_tag }}"
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: BASE_RETURNS_URL=${{ env.BASE_RETURNS_URL }} npm run test
      - name: Get and update the release
        shell: bash
        run: |
          get_tag_url="https://api.github.com/repos/RueLaLa/${{ github.event.client_payload.application }}/releases/tags/${{ github.event.client_payload.release_tag }}"
          release_url=$(curl --location --request GET "$get_tag_url" --header 'Content-Type: application/json' --header 'Accept: application/vnd.github.nebula-preview+json' --header 'Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}' | grep '"url"' | grep "${{ github.event.client_payload.application }}" | sed -e 's/[ \t]*"url":[ \t]*//' -e 's/[",]//g')
          echo "Release URL: $release_url"
          echo "Patching release: ${{ github.event.client_payload.release_tag }}"
          curl --fail --location --request PATCH "$release_url" --header 'Content-Type: application/json' --header 'Accept: application/vnd.github.nebula-preview+json' --header 'Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}' -d '{"prerelease": false}'
          
